In [1]:
matriz = []


for i in range(3):
    matriz.append([None]*3)
    

In [2]:
a = {'asdf':0}
a['asdf']

0

In [2]:
def bg():
    w = 300
    h = 300

    var_w = 300/3
    var_h = 300/3

    matriz
    for index, i in enumerate(matriz):
        for index_j, j in enumerate(i):
                
                matriz[index][index_j] = (var_w*(index_j+1), var_h*index)

In [3]:
import numpy as np
import random
lista = [0]*7 + [1]*6 + [-1]*3
random.shuffle(lista)

lista = np.array(lista)

matriz_prob = lista.reshape(-1, 4)
matriz_prob

array([[ 0,  1,  0,  0],
       [ 1, -1, -1,  1],
       [ 1, -1,  1,  0],
       [ 0,  0,  0,  1]])

In [4]:
matriz_prob[0]

array([0, 1, 0, 0])

In [5]:
a = (0, 100)
b = (2, 500)
import math
print(math.dist(a, b))
#print(math.isclose(a, b, abs_tol=1))


400.0049999687504


In [6]:
l = 0
for i in range(2):
    for k in range(2):
        print(l)
        l+=1

0
1
2
3


In [7]:
import numpy as np
import random
lista = [0]*7 + [1]*6 + [-1]*3
random.shuffle(lista)

lista = np.array(lista)

matriz_prob = lista.reshape(-1, 4)
matriz_prob


w = 300
h = 300

var_w = 300/3
var_h = 300/3

matriz
for index, i in enumerate(matriz):
    for index_j, j in enumerate(i):            
        matriz[index][index_j] = {'valor': matriz_prob[index][index_j].item()}

    print(i)
    
    

[{'valor': 0}, {'valor': 1}, {'valor': 0}]
[{'valor': -1}, {'valor': 0}, {'valor': 1}]
[{'valor': 1}, {'valor': 0}, {'valor': 0}]


In [8]:
matriz[1]

[{'valor': -1}, {'valor': 0}, {'valor': 1}]

In [62]:
       
## Matriz Crua
matriz = []
for i in range(4):
    matriz.append([None]*4)
## Preenchendo com as coordenadas
posic_relativa = 0
for index, i in enumerate(matriz):    
    
    for index_j, j in enumerate(i):        
    
        
        matriz[index][index_j] = {'valor': matriz_prob[index][index_j].item(), 'posicao_relativa': posic_relativa, 'posicao_ralativa_h_matriz': index_j, 'posicao_ralativa_v_matriz': index}
        
        posic_relativa+=1
        
        print('| H:',matriz[index][index_j]['posicao_ralativa_h_matriz'], 'V:',matriz[index][index_j]['posicao_ralativa_v_matriz'], 'v:',matriz[index][index_j]['valor'], 'R:',matriz[index][index_j]['posicao_relativa'], end=' ')
    print()
print('--------------------')     
for index, i in enumerate(matriz):    
    for index_j, j in enumerate(i):
        print(i[index_j]['valor'], end=' ')
    print()

| H: 0 V: 0 v: 0 R: 0 | H: 1 V: 0 v: 1 R: 1 | H: 2 V: 0 v: 0 R: 2 | H: 3 V: 0 v: -1 R: 3 
| H: 0 V: 1 v: -1 R: 4 | H: 1 V: 1 v: 0 R: 5 | H: 2 V: 1 v: 1 R: 6 | H: 3 V: 1 v: 1 R: 7 
| H: 0 V: 2 v: 1 R: 8 | H: 1 V: 2 v: 0 R: 9 | H: 2 V: 2 v: 0 R: 10 | H: 3 V: 2 v: -1 R: 11 
| H: 0 V: 3 v: 1 R: 12 | H: 1 V: 3 v: 0 R: 13 | H: 2 V: 3 v: 0 R: 14 | H: 3 V: 3 v: 1 R: 15 
--------------------
0 1 0 -1 
-1 0 1 1 
1 0 0 -1 
1 0 0 1 


In [100]:
n = 0

In [ ]:
count = 0
len_matriz = len(matriz)
qtd_trofeu = 0


## Search_matriz é para buscar os baús da próximidade
def search_matriz(p_horizontal:int, p_vertical:int, matriz=matriz) -> int: 
    h_min = matriz[0][0]['posicao_ralativa_h_matriz']
    h_max = matriz[0][-1]['posicao_ralativa_h_matriz']
    v_min = matriz[0][0]['posicao_ralativa_v_matriz']
    v_max = matriz[-1][-1]['posicao_ralativa_v_matriz']
    
    result = 0
    if (p_horizontal >= h_min and p_vertical >= v_min):
        if (p_horizontal <= h_max and p_vertical <= v_max):
            if matriz[p_vertical][h]['valor'] == 1:
                result = 1

    return result
    
posicao_h = 0
posicao_v = 0
for i in matriz:
    for j in i:
        if j['posicao_relativa'] == n:
            posicao_h = j['posicao_ralativa_h_matriz']
            posicao_v = j['posicao_ralativa_v_matriz']
            break

print('posição n: ',posicao_h, posicao_v)     
qtd_trofeu += search_matriz(posicao_h+1, posicao_v)
qtd_trofeu += search_matriz(posicao_h-1, posicao_v)
qtd_trofeu += search_matriz(posicao_h, posicao_v-1)
qtd_trofeu += search_matriz(posicao_h, posicao_v+1)
      
print(qtd_trofeu)
            

posição n:  0 0
{'valor': 1, 'posicao_relativa': 1, 'posicao_ralativa_h_matriz': 1, 'posicao_ralativa_v_matriz': 0}
1


In [ ]:
for index, i in enumerate(matriz):    
    ## Verificando se está na linha zero
    if index == 0:
        validacao = False
        for element in i:
            if element['posicao_relativa'] == n:
                validacao = True
                posicao = element['posicao_ralativa_matriz']
        
        if validacao:
            qtd_trofeu += asdk((posicao-1), i)
            qtd_trofeu += asdk((posicao+1), i)
            qtd_trofeu += asdk((posicao), matriz[index+1])
            break
    
    else:
        posicao = element['posicao_ralativa_matriz']
        qtd_trofeu += asdk((posicao-1), i)
        qtd_trofeu += asdk((posicao+1), i)
        qtd_trofeu += asdk((posicao), matriz[index+1])
        qtd_trofeu += asdk((posicao), matriz[index-1])
        break
        
    ## Verificando se está na última linha
    if index == len_matriz-1:
        validacao = False
        for element in i:
            if element['posicao_relativa'] == n:
                validacao = True
                posicao = element['posicao_ralativa_matriz']
        
        if validacao:
            qtd_trofeu += asdk((posicao-1), i)
            qtd_trofeu += asdk((posicao+1), i)
            qtd_trofeu += asdk((posicao), matriz[index-1])

In [18]:
matriz

[[{'posicao': (0.0, 0.0), 'valor': 1},
  {'posicao': (100.0, 0.0), 'valor': 1},
  {'posicao': (200.0, 0.0), 'valor': 1},
  {'posicao': (300.0, 0.0), 'valor': 0}],
 [{'posicao': (0.0, 100.0), 'valor': -1},
  {'posicao': (100.0, 100.0), 'valor': 0},
  {'posicao': (200.0, 100.0), 'valor': 0},
  {'posicao': (300.0, 100.0), 'valor': 0}],
 [{'posicao': (0.0, 200.0), 'valor': 0},
  {'posicao': (100.0, 200.0), 'valor': 1},
  {'posicao': (200.0, 200.0), 'valor': 1},
  {'posicao': (300.0, 200.0), 'valor': 0}],
 [{'posicao': (0.0, 300.0), 'valor': -1},
  {'posicao': (100.0, 300.0), 'valor': 0},
  {'posicao': (200.0, 300.0), 'valor': 1},
  {'posicao': (300.0, 300.0), 'valor': -1}]]

In [17]:
k = (676, 141)
lista = []
for index, i in enumerate(matriz):
    for index_j, j in enumerate(i):
        val_matriz = matriz[index][index_j]
        distancia = math.dist(k, val_matriz)  
        lista.append({'dist': distancia, 'val_matriz': val_matriz})

TypeError: must be real number, not str

In [ ]:
lista

array([ 1,  1,  0,  0,  1, -1,  1,  0,  0,  1, -1,  0, -1,  0,  1,  0])

In [ ]:
for i in matriz:
    for k in i:
        print(k)

{'posicao': (0.0, 0.0), 'valor': 1}
{'posicao': (100.0, 0.0), 'valor': -1}
{'posicao': (200.0, 0.0), 'valor': 1}
{'posicao': (300.0, 0.0), 'valor': 1}
{'posicao': (0.0, 100.0), 'valor': 1}
{'posicao': (100.0, 100.0), 'valor': 0}
{'posicao': (200.0, 100.0), 'valor': 1}
{'posicao': (300.0, 100.0), 'valor': 0}
{'posicao': (0.0, 200.0), 'valor': 0}
{'posicao': (100.0, 200.0), 'valor': -1}
{'posicao': (200.0, 200.0), 'valor': 0}
{'posicao': (300.0, 200.0), 'valor': 0}
{'posicao': (0.0, 300.0), 'valor': 0}
{'posicao': (100.0, 300.0), 'valor': 1}
{'posicao': (200.0, 300.0), 'valor': 0}
{'posicao': (300.0, 300.0), 'valor': -1}


In [ ]:
matriz[0][0]

{'posicao': (0.0, 0.0), 'valor': 1}

In [20]:
jogada = [
        {'jogada_atual':0 , 'player_atual': 'play_01'},
        {'jogada_anterior':0 , 'player_anterior': 'play_02'}
    ]

In [23]:
for k in jogada:
    for a,b in k.items():
        print(a)

jogada_atual
player_atual
jogada_anterior
player_anterior


In [1]:
history_points = {'play_01': 0, 'play_02':0}
jogada = {'jogada_atual':0 , 'player_atual': 'play_01','jogada_anterior':0 , 'player_anterior': 'play_02'}

In [19]:
h = 1

In [31]:

def a (b):
    b+=1
    return b
    
h = a(h)
print(h)

13


In [33]:
b = ['a', 'aa', 'aaa']

if 'a1' in b:
    print(1)

In [48]:
from tqdm import tqdm
import time

for i in tqdm(range(60*5, 0, -1)):
    a
    time.sleep(0.02)


100%|██████████| 300/300 [00:06<00:00, 49.26it/s]


In [16]:
## 2

texto = input("Digite: ")
texto_temp = ''

for i in range(1, len(texto)+1):
    texto_temp+= texto[-i]

print(texto_temp)

fdsa


In [17]:
## 3

numero = input('Digite')

if 'i' in numero:
    numero = numero.split('-')
    numero = numero[0]+numero[1]

if not len(numero) == 9:
    numero = "9"+numero

print(numero)

9982-1123


In [18]:
## 4
texto = input('Digite: ')
for i in range(len(texto)):
    temp = texto[0:i]
    print(temp)


a
as
asd
asdf
asdfa
asdfas


In [ ]:
matriz = [ [[None]*3]*3 ]


for id1, i in enumerate(matriz):
    for id2, j in enumerate(i):
        matriz[id1][id2] = input('Digite')

encontrar = input('Encontrar: ')
encontrado = False

for id1, i in enumerate(matriz):
    if encontrar in i:
        print('Encontrado')
        encontrado = True
        break

if not encontrado: print('Não foi encontrado')

[[[None, None, None], [None, None, None], [None, None, None]]]


KeyboardInterrupt: Interrupted by user

In [8]:
import random  
lista = [0]*(7) + [1]*6 + [-1]*3
random.shuffle(lista)

matriz = []
count = 0
for i in range(4):
    matriz.append([None]*4)
    
for i in range(4):
    for k in range(4):
        matriz[i][k] = lista[count]
        count+=1

    
matriz 

[[0, 1, 0, -1], [1, 0, 1, 0], [1, 0, 1, -1], [0, -1, 0, 1]]