In [22]:
matriz = []


for i in range(3):
    matriz.append([None]*3)
    

In [20]:
print(a[1][1])

None


In [ ]:
def bg():
    w = 300
    h = 300

    var_w = 300/3
    var_h = 300/3

    matriz
    for index, i in enumerate(matriz):
        for index_j, j in enumerate(i):
                
                matriz[index][index_j] = (var_w*(index_j+1), var_h*index)

In [ ]:
import random
lista = [0]* + [1]*6 + [-1]*3
random.shuffle(lista)
print(lista)

[1, -1, -1, 1, 1, -1, 0, 1, 0, 0, 1, 1]


In [72]:
matriz = []
for i in range(4):
    matriz.append([None]*4)

In [73]:
import numpy as np
import random
lista = [0]*7 + [1]*6 + [-1]*3
random.shuffle(lista)

lista = np.array(lista)

matriz_prob = lista.reshape(-1, 4)
matriz_prob

array([[ 1,  0,  0,  1],
       [ 1,  0, -1, -1],
       [ 0,  0,  1, -1],
       [ 1,  0,  0,  1]])

In [77]:
matriz_prob[0]

array([1, 0, 0, 1])

In [108]:
a = (0, 100)
b = (2, 500)
import math
print(math.dist(a, b))
#print(math.isclose(a, b, abs_tol=1))


400.0049999687504


In [103]:
l = 0
for i in range(2):
    for k in range(2):
        print(l)
        l+=1

0
1
2
3


In [106]:
import numpy as np
import random
lista = [0]*7 + [1]*6 + [-1]*3
random.shuffle(lista)

lista = np.array(lista)

matriz_prob = lista.reshape(-1, 4)
matriz_prob


w = 300
h = 300

var_w = 300/3
var_h = 300/3

matriz
for index, i in enumerate(matriz):
    for index_j, j in enumerate(i):            
        matriz[index][index_j] = {'posicao': (var_w*(index_j), var_h*index), 'valor': matriz_prob[index][index_j].item()}

    print(i)
    
    

[{'posicao': (0.0, 0.0), 'valor': 1}, {'posicao': (100.0, 0.0), 'valor': -1}, {'posicao': (200.0, 0.0), 'valor': 1}, {'posicao': (300.0, 0.0), 'valor': 1}]
[{'posicao': (0.0, 100.0), 'valor': 1}, {'posicao': (100.0, 100.0), 'valor': 0}, {'posicao': (200.0, 100.0), 'valor': 1}, {'posicao': (300.0, 100.0), 'valor': 0}]
[{'posicao': (0.0, 200.0), 'valor': 0}, {'posicao': (100.0, 200.0), 'valor': -1}, {'posicao': (200.0, 200.0), 'valor': 0}, {'posicao': (300.0, 200.0), 'valor': 0}]
[{'posicao': (0.0, 300.0), 'valor': 0}, {'posicao': (100.0, 300.0), 'valor': 1}, {'posicao': (200.0, 300.0), 'valor': 0}, {'posicao': (300.0, 300.0), 'valor': -1}]


In [110]:
matriz[0][0]['valor']

1

In [111]:
k = (676, 141)
lista = []
for index, i in enumerate(matriz):
    for index_j, j in enumerate(i):
        val_matriz = matriz[index][index_j]
        distancia = math.dist(k, val_matriz)  
        lista.append({'dist': distancia, 'val_matriz': val_matriz})

TypeError: must be real number, not str

In [104]:
lista

array([ 1,  1,  0,  0,  1, -1,  1,  0,  0,  1, -1,  0, -1,  0,  1,  0])

In [113]:
for i in matriz:
    for k in i:
        print(k)

{'posicao': (0.0, 0.0), 'valor': 1}
{'posicao': (100.0, 0.0), 'valor': -1}
{'posicao': (200.0, 0.0), 'valor': 1}
{'posicao': (300.0, 0.0), 'valor': 1}
{'posicao': (0.0, 100.0), 'valor': 1}
{'posicao': (100.0, 100.0), 'valor': 0}
{'posicao': (200.0, 100.0), 'valor': 1}
{'posicao': (300.0, 100.0), 'valor': 0}
{'posicao': (0.0, 200.0), 'valor': 0}
{'posicao': (100.0, 200.0), 'valor': -1}
{'posicao': (200.0, 200.0), 'valor': 0}
{'posicao': (300.0, 200.0), 'valor': 0}
{'posicao': (0.0, 300.0), 'valor': 0}
{'posicao': (100.0, 300.0), 'valor': 1}
{'posicao': (200.0, 300.0), 'valor': 0}
{'posicao': (300.0, 300.0), 'valor': -1}


In [115]:
matriz[0][0]

{'posicao': (0.0, 0.0), 'valor': 1}